"""new fields in user model

Revision ID: 983b48b6f738
Revises: f2a155ab6446
Create Date: 2019-07-27 14:26:14.655846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983b48b6f738'
down_revision = 'f2a155ab6446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
